// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class kucukdgsklk3geriislem3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kucukdgsklk3geriislem3));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081149063_kucukdgsklk3geriislem3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
