// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class makaleyeetiketekledm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makaleyeetiketekledm));
        
        string IMigrationMetadata.Id
        {
            get { return "201801071628181_makaleyeetiketekledm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
