// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class yorumtablosudegişiklik2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yorumtablosudegişiklik2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801071803507_yorumtablosudegişiklik2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
